version: '3.7'

services:
    mariadb:
        image: mariadb:latest
        container_name: 'mariadb-flask'
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=mariadb
            - PMA_USER=${DB_USER}
            - PMA_PASSWORD=${DB_PASS}
        ports:
            - "8080:80"
        depends_on:
            - mariadb
