"""remove projects and add new relations

Revision ID: 71e7f059dfb6
Revises: f69517e7a840
Create Date: 2023-03-24 15:14:07.753339

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "71e7f059dfb6"
down_revision = "f69517e7a840"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipes_tarefas",
        sa.Column("equipe_id", sa.Integer(), nullable=False),
        sa.Column("tarefa_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipe_id"],
            ["equipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tarefa_id"],
            ["tarefas.id"],
        ),
        sa.PrimaryKeyConstraint("equipe_id", "tarefa_id"),
    )
    op.create_table(
        "usuarios_equipes",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("equipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipe_id"],
            ["equipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("usuario_id", "equipe_id"),
    )
    op.create_table(
        "usuarios_tarefas",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("tarefa_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tarefa_id"],
            ["tarefas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("usuario_id", "tarefa_id"),
    )
    op.drop_table("projetos")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projetos",
        sa.Column(
            "id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("usuarios_tarefas")
    op.drop_table("usuarios_equipes")
    op.drop_table("equipes_tarefas")
    # ### end Alembic commands ###
