"""add email and password to User model

Revision ID: f319815bf7d6
Revises: f8cd86bf14f2
Create Date: 2023-02-17 11:57:59.026664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f319815bf7d6"
down_revision = "f8cd86bf14f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuario", sa.Column("email", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "usuario", sa.Column("password", sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "password")
    op.drop_column("usuario", "email")
    # ### end Alembic commands ###
